In [280]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [281]:
bat = pd.read_csv('final_batting_df.csv')
bat.head()

Match_id     Team Opposite_Team  Innings         Batsman Dismissal Type  \
0         1  England   New Zealand        1  Jonny Bairstow          Catch   
1         1  England   New Zealand        1     Dawid Malan          Catch   
2         1  England   New Zealand        1        Joe Root         Bowled   
3         1  England   New Zealand        1     Harry Brook          Catch   
4         1  England   New Zealand        1       Moeen Ali         Bowled   

          Fielder            Bowler  Runs  Balls  Boundaries  Sixes  \
0  Daryl Mitchell  Mitchell Santner    33     35           4      1   
1          Latham        Matt Henry    14     24           2      0   
2               -    Glenn Phillips    77     86           4      1   
3    Devon Conway   Rachin Ravindra    25     16           4      1   
4               -    Glenn Phillips    11     17           1      0   

   StrikeRate  
0       94.29  
1       58.33  
2       89.53  
3      156.25  
4       64.71

In [282]:
bowl = pd.read_csv('final_bowling_df.csv')
bowl.head()

Match_id         Team Opposite_Team  Innings            Bowler  Overs  \
0         1  New Zealand       England        1       Trent Boult   10.0   
1         1  New Zealand       England        1        Matt Henry   10.0   
2         1  New Zealand       England        1  Mitchell Santner   10.0   
3         1  New Zealand       England        1     Jimmy Neesham    7.0   
4         1  New Zealand       England        1   Rachin Ravindra   10.0   

   Maindens  Runs  Wickets  No_Balls  Wides  Economy  
0         1    48        1         0      1      4.8  
1         1    48        3         0      0      4.8  
2         0    37        2         0      1      3.7  
3         0    56        0         0      4      8.0  
4         0    76        1         0      0      7.6

In [283]:
sch = pd.read_csv('schedule.csv')
sch.head()

Match_id                      Match         Team1        Team2  \
0         1     ENGLAND vs NEW ZEALAND       England  New zealand   
1         2    PAKISTAN vs NETHERLANDS      Pakistan  Netherlands   
2         3  BANGLADESH vs AFGHANISTAN    Bangladesh  Afghanistan   
3         4  SOUTH AFRICA vs SRI LANKA  South africa    Sri lanka   
4         5         INDIA vs AUSTRALIA         India    Australia   

                                          Venue        City        Winner  \
0                         Narendra Modi Stadium   Ahmedabad   New Zealand   
1            Rajiv Gandhi International Stadium   Hyderabad      Pakistan   
2  Himachal Pradesh Cricket Association Stadium  Dharamsala    Bangladesh   
3                          Arun Jaitley Stadium       Delhi  South Africa   
4                        MA Chidambaram Stadium     Chennai         India   

     Won_By Player_of_the_Match  \
0    9 wkts     Rachin Ravindra   
1   81 runs        Saud Shakeel   
2    6 wkts  Mehidy Hasan Miraz   
3  102 runs       Aiden Markram   
4    6 wkts            KL Rahul   

                                          Match_Info  
0  https://www.cricbuzz.com/live-cricket-scorecar...  
1  https://www.cricbuzz.com/live-cricket-scorecar...  
2  https://www.cricbuzz.com/live-cricket-scorecar...  
3  https://www.cricbuzz.com/live-cricket-scorecar...  
4  https://www.cricbuzz.com/live-cricket-scorecar...

#### Is Rohit scores in powerplay impacted India total scores in First Batting and while chasing helped India Winning ?

In [284]:
#sch[(sch['Team1'] == 'India') & (sch['Won_By'].str.contains('wkts'))] # 2nd innings or chasing 
india_chasing_mat_ids = sch[(sch['Winner'] == 'India') & (sch['Won_By'].str.contains('wkts'))]['Match_id'].values
india_batting_mat_ids = sch[(sch['Winner'] == 'India') & (~sch['Won_By'].str.contains('wkts'))]['Match_id'].values
india_chasing_mat_ids,india_batting_mat_ids

(array([ 5,  9, 12, 17, 21], dtype=int64),
 array([29, 33, 37, 45, 46], dtype=int64))

In [285]:
# Rohit Sharma Chasing Runs 
rohit_chasing_runs = bat[(bat['Match_id'].isin(india_chasing_mat_ids)) & (bat['Batsman'] == 'Rohit Sharma')]['Runs'].values
rohit_batting_runs = bat[(bat['Match_id'].isin(india_batting_mat_ids)) & (bat['Batsman'] == 'Rohit Sharma')]['Runs'].values
rohit_chasing_runs,rohit_batting_runs

(array([  0, 131,  86,  48,  46], dtype=int64),
 array([87,  4, 40, 61, 47], dtype=int64))

In [286]:
runs = [47,87,4,40,61,47]
powerplay = [80,35,60,91,91,84]
India_total = [240,229,357,326,410,397]
Result = [False,True,True,True,True,True]

runs_c = [0,131,86,48,46]
powerplay_c = [27,94,79,63,63]
India_total_c = [201,273,197,261,274]
Result_c = [True,True,True,True,True]

correlation_powerplay_total = np.corrcoef(powerplay, India_total)[0, 1]
print("Correlation between powerplay runs and India's total score:", str(round(correlation_powerplay_total*100,2))+'%')
correlation_powerplay_total = np.corrcoef(powerplay_c, India_total_c)[0, 1]
print("Correlation between powerplay runs and India's total score:", str(round(correlation_powerplay_total*100,2))+'%')

Correlation between powerplay runs and India's total score: 58.38%
Correlation between powerplay runs and India's total score: 44.48%


#### 1st Batting in Chennai could consider them winners + Chennai pitch is Favoured to the Spinner (If Needed do Analysis for Lucknow Also )

In [287]:
#sch[sch['City'] == 'Chennai']['Won_By'].str.contains('wkts').count()
chennai = sch[sch['City']=='Chennai']
chennai[chennai['Won_By'].str.contains('wkt')].shape[0]/chennai.shape[0]*100

80.0

In [288]:
chennai_match_ids = chennai.Match_id.values
chennai_match_ids

array([ 5, 11, 16, 22, 26], dtype=int64)

In [289]:
c_bowl = bowl[bowl['Match_id'].isin(chennai_match_ids)]

In [290]:
import pandas as pd

# Create a list of player data with corrected categories
players = [
    ["Jasprit Bumrah", "Seamer"],
    ["Mohammed Siraj", "Seamer"],
    ["Hardik Pandya", "Seamer"],  # Updated to "Seamer" assuming predominant bowling style
    ["Ravichandran Ashwin", "Spinner"],
    ["Kuldeep Yadav", "Spinner"],
    ["Ravindra Jadeja", "Spinner"],
    ["Trent Boult", "Seamer"],
    ["Matt Henry", "Seamer"],
    ["Lockie Ferguson", "Seamer"],
    ["Mitchell Santner", "Spinner"],
    ["Glenn Phillips", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Rachin Ravindra", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Daryl Mitchell", "Seamer"],  # Updated to "Seamer" assuming predominant bowling style
    ["Mujeeb Ur Rahman", "Spinner"],
    ["Fazalhaq Farooqi", "Seamer"],
    ["Naveen-ul-Haq", "Seamer"],
    ["Mohammad Nabi", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Rashid Khan", "Spinner"],
    ["Azmatullah Omarzai", "Seamer"],
    ["Noor Ahmad", "Spinner"],
    ["Marco Jansen", "Seamer"],
    ["Lungi Ngidi", "Seamer"],
    ["Markram", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Maharaj", "Spinner"],
    ["Gerald Coetzee", "Seamer"],
    ["Shamsi", "Spinner"],
    ["Mitchell Starc", "Seamer"],
    ["Josh Hazlewood", "Seamer"],
    ["Pat Cummins", "Seamer"],
    ["Glenn Maxwell", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Cameron Green", "Seamer"],  # Updated to "Seamer" assuming predominant bowling style
    ["Adam Zampa", "Spinner"],
    ["Mustafizur Rahman", "Seamer"],
    ["Shoriful Islam", "Seamer"],
    ["Taskin Ahmed", "Seamer"],
    ["Shakib Al Hasan", "Spinner"],  # Updated to "Spinner" assuming predominant bowling style
    ["Mehidy Hasan Miraz", "Spinner"],
    ["Shaheen Afridi", "Seamer"],
    ["Hasan Ali", "Seamer"],
    ["Haris Rauf", "Seamer"],
    ["Usama Mir", "Spinner"],
    ["Shadab Khan", "Spinner"],
    ["Iftikhar Ahmed", "Spinner"],
    ["Mohammad Nawaz", "Spinner"],
    ["Mohammad Wasim Jr", "Seamer"],
]

# Create a DataFrame from the list of players
df = pd.DataFrame(players, columns=["Player Name", "Bowler Type"])

In [291]:
df2 = pd.merge(left=c_bowl,right=df,left_on='Bowler',right_on='Player Name',how='inner')
round(df2.groupby('Bowler Type')['Wickets'].count() / df2.shape[0]*100)

Bowler Type
Seamer     52.0
Spinner    48.0
Name: Wickets, dtype: float64

#### South Africa 1st Inning score is morethan 300 in that south Africa Won 


In [292]:
south_africa_first_300 = bat[(bat['Team'] == 'South Africa') & (bat['Innings'] == 1)]['Match_id'].unique()
south_africa_first_300

array([ 4, 10, 20, 23, 32, 47], dtype=int64)

In [293]:
round(sch[sch['Match_id'].isin(south_africa_first_300) & (sch['Winner'] == 'South Africa')].shape[0]/len(south_africa_first_300)*100,2)

83.33